import type { ApiSessionDetail } from '../shared/api-client';
import type { GitHubExportConfig } from '../shared/types';

export interface GitHubIssueAnalysisHint {
  summary?: string;
  rootCause?: string;
  classification?: string;
  actions?: string[];
  suggestedFiles?: string[];
}

export interface GitHubIssueCreateResult {
  issueUrl: string;
  issueNumber: number;
  title: string;
}

function splitCsv(input: string): string[] {
  return input
    .split(',')
    .map((item) => item.trim())
    .filter((item) => item.length > 0);
}

function truncate(input: string, maxLength: number): string {
  return input.length > maxLength ? `${input.slice(0, maxLength - 3)}...` : input;
}

function normalizeErrorSummary(session: ApiSessionDetail): string {
  if (session.error?.message) {
    return session.error.message;
  }

  const errorEvent = session.events.find((event) => event.type === 'error');
  if (errorEvent && typeof errorEvent.payload?.message === 'string') {
    return errorEvent.payload.message;
  }

  return 'No explicit runtime error captured.';
}

function buildIssueTitle(session: ApiSessionDetail, analysis?: GitHubIssueAnalysisHint): string {
  const host = (() => {
    try {
      return new URL(session.url).host;
    } catch {
      return 'unknown-host';
    }
  })();

  const root = analysis?.rootCause?.trim() || normalizeErrorSummary(session);
  return truncate(`[BugCatcher] ${root} (${host})`, 120);
}

function renderList(items: string[] | undefined): string {
  if (!items || items.length === 0) {
    return '- N/A';
  }

  return items.map((item) => `- ${item}`).join('\n');
}

function buildIssueBody(session: ApiSessionDetail, analysis?: GitHubIssueAnalysisHint): string {
  const createdAt = new Date(session.createdAt).toISOString();
  const errorSummary = normalizeErrorSummary(session);

  return [
    '## Bug Summary',
    analysis?.summary?.trim() || 'Captured via BugCatcher replay workflow.',
    '',
    '## Likely Root Cause',
    analysis?.rootCause?.trim() || errorSummary,
    '',
    '## Classification',
    analysis?.classification?.trim() || 'unclassified',
    '',
    '## Suggested Files',
    renderList(analysis?.suggestedFiles),
    '',
    '## Recommended Actions',
    renderList(analysis?.actions),
    '',
    '## Session Context',
    `- Session ID: ${session.sessionId}`,
    `- Captured URL: ${session.url}`,
    `- Captured At: ${createdAt}`,
    `- Error Signal: ${errorSummary}`,
    `- Console Events: ${session.stats.consoleCount}`,
    `- Network Events: ${session.stats.networkCount}`,
    `- State Snapshots: ${session.stats.stateSnapshots}`,
    '',
    '---',
    'Generated by BugCatcher extension export flow.',
  ].join('\n');
}

export function validateGitHubExportConfig(config: GitHubExportConfig): string | null {
  if (!config.enabled) {
    return 'GitHub export is disabled. Enable it in options before exporting.';
  }

  if (!config.owner.trim()) {
    return 'GitHub owner is required before exporting.';
  }

  if (!config.repo.trim()) {
    return 'GitHub repository name is required before exporting.';
  }

  if (!config.token.trim()) {
    return 'GitHub token is required before exporting.';
  }

  return null;
}

export async function createGitHubIssue(
  config: GitHubExportConfig,
  session: ApiSessionDetail,
  analysis?: GitHubIssueAnalysisHint,
): Promise<GitHubIssueCreateResult> {
  const validationError = validateGitHubExportConfig(config);
  if (validationError) {
    throw new Error(validationError);
  }

  const endpoint = `https://api.github.com/repos/${encodeURIComponent(config.owner)}/${encodeURIComponent(config.repo)}/issues`;
  const response = await fetch(endpoint, {
    method: 'POST',
    headers: {
      Accept: 'application/vnd.github+json',
      'Content-Type': 'application/json',
      Authorization: `Bearer ${config.token}`,
      'X-GitHub-Api-Version': '2022-11-28',
    },
    body: JSON.stringify({
      title: buildIssueTitle(session, analysis),
      body: buildIssueBody(session, analysis),
      labels: splitCsv(config.labels),
      assignees: splitCsv(config.assignees),
    }),
  });

  const payload = (await response.json()) as {
    html_url?: string;
    number?: number;
    title?: string;
    message?: string;
    errors?: Array<{ message?: string }>;
  };

  if (!response.ok) {
    const errorMessage = payload.message || payload.errors?.[0]?.message || `GitHub API returned ${response.status}`;
    throw new Error(`GitHub export failed: ${errorMessage}`);
  }

  if (!payload.html_url || typeof payload.number !== 'number' || !payload.title) {
    throw new Error('GitHub export failed: response did not include issue URL.');
  }

  return {
    issueUrl: payload.html_url,
    issueNumber: payload.number,
    title: payload.title,
  };
}
